Add bookings
dima-irqtsk/java-shareit pull request #2
Opened 2023-06-26 09:55 UTC by dima-irqtsk

Привет!
Ну и тяжелый же спринт был )

2023-06-26 17:51 UTC, ohelly requested changes
Привет! Видно, что проделана большая работа. Оставил несколько замечаний, которые необходимо исправить. Также оставил ряд рекомендаций, на которые стоит обратить внимание

2023-06-26 17:51 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Data
Рекомендация: Аннотацию ``@Data`` не рекомендуется использовать над сущностями, тут есть объяснение
https://habr.com/ru/companies/haulmont/articles/564682/

2023-06-26 17:51 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +                && ((itemDto.getName() != null) || (itemDto.getDescription() != null))) {
Рекомендация: Считаю, что проверка на name и description здесь лишняя, так как ниже по коду все равно проверяется

2023-06-26 17:51 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +        if (itemDto.getLastBooking() == null && itemDto.getNextBooking() != null) {
Не совсем понимаю, почему next становится на место last 😄

2023-06-26 17:51 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +        for (Item item : itemRepository.findAll()) {
Необходимо исправить: Искать по подстроке лучше сразу запросом в БД, иначе получается, что это очень тяжелая операция. Если представить, что в БД сотни тысяч записей, то после findAll они все выгрузятся в память приложения, что может привести к завершению работы.

2023-06-26 17:51 UTC, ohelly commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +        User user = userRepository.findById(userId)
Рекомендация: Можно использовать метод getById из UserService, там уже есть проверка на то, существует ли пользователь.
Аналогично и для item

2023-06-26 17:52 UTC, ohelly commented
> Привет! Ну и тяжелый же спринт был )

Дальше будет посложнее)

2023-06-27 04:42 UTC, dima-irqtsk commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +                && ((itemDto.getName() != null) || (itemDto.getDescription() != null))) {
Когда я писал эту часть метода, я руководствовался следующим домыслом.
От пользователя приходит джейсон для изменения предмета. Если пользователь является владельцем предмета, то он может поменять любые поля предмета — название, описание и доступность. Если пользователь не является владельцем предмета, то он может изменить только доступность. Ему нужен доступ к такому функционалу, потому что он взял предмет в аренду, тогда предмет должен стать недоступен.
Пока оставлю код без изменений. Если что, убрать проверку не долго.
Справедливости ради, отмечу, что если оставить возможность менять доступность только у владельца, то тесты всё равно все проходят.

2023-06-27 04:43 UTC, dima-irqtsk commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +                && ((itemDto.getName() != null) || (itemDto.getDescription() != null))) {
Не, убрал проверку. Ты прав.

2023-06-27 04:47 UTC, dima-irqtsk commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +        if (itemDto.getLastBooking() == null && itemDto.getNextBooking() != null) {
Это потому что кое-кто писал код 15 часов подряд )
Удалил.

2023-06-27 05:29 UTC, dima-irqtsk commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +        User user = userRepository.findById(userId)
С юзером исправил, а с предметом не выйдет. Метод getById из ItemService у меня возвращает не Item, а ItemDto.
А в поле коммента нужно положить именно Item.

2023-06-27 06:20 UTC, dima-irqtsk commented on src/main/java/ru/practicum/shareit/item/impl/ItemServiceImpl.java
> +        for (Item item : itemRepository.findAll()) {
Это отличное замечание, спасибо )
Ну и заодно перенес маппинг в сервисный слой. А то он у меня был раскидан там и сям.

Кстати, когда переносил маппинг, пришлось в методе добавления комментариев вернуть как было, потому что getById() теперь возвращает ДТОшку, а не полноценный объект.

2023-06-27 19:23 UTC, ohelly approved these changes
Привет! Все супер, исправлены все замечания. Можно двигаться дальше!

2023-06-29 06:22 UTC, merged