Add item requests
dima-irqtsk/java-shareit pull request #3
Opened 2023-07-07 10:25 UTC by dima-irqtsk

Судя по всему, этот спринт был уроком, что тесты нужно писать вместе с основным кодом, а не кучей потом )

2023-07-09 19:56 UTC, ohelly commented
> Судя по всему, этот спринт был уроком, что тесты нужно писать вместе с основным кодом, а не кучей потом )

На самом деле - да, не знаю почему в курсе выбран другой подход.
Есть еще одна техника разработки - TDD(test driven development). Ее суть в том, что сначала пишутся тесты, а потом под них уже основной код, довольно популярная и у нее есть много плюсов, можешь почитать на досуге если интересно.

2023-07-09 20:13 UTC, ohelly requested changes
Привет! В целом отличная работа, все работает корректно. Есть пара замечаний, которые необходимо исправить связанных с производительностью. Также еоставил пару рекомендаций.

2023-07-09 20:13 UTC, ohelly commented on src/main/java/ru/practicum/shareit/request/impl/ItemRequestServiceImpl.java
> +                .created(LocalDateTime.now())
Рекомендация: Для того чтобы вручную не ставить дату можно воспользоваться функционалом хибернейта. Данная аннотация говорит хибере проставить дату при вставке данных

![image](https://github.com/dima-irqtsk/java-shareit/assets/51891976/5901060a-4d1c-4248-9992-9363da8a6da6)

2023-07-09 20:13 UTC, ohelly commented on src/main/java/ru/practicum/shareit/request/impl/ItemRequestServiceImpl.java
> +        itemRequestDtos.forEach(this::setItemsToItemRequestDto);
Необходимо исправить: Запрос внутри метода setItemsToItemRequestDto выполняется N раз для N itemRequest. Будет лучше сделать одним запросом с помощью оператора IN и HashMap, как было в проекте filmorate

2023-07-09 20:13 UTC, ohelly commented on src/main/java/ru/practicum/shareit/request/impl/ItemRequestServiceImpl.java
> +    private void checkParameters(int from, int size) {
Рекомендация: Данную проверку можно сделать с помощью аннотаций ``@Min`` и ``@Max`` в контроллере

2023-07-09 20:13 UTC, ohelly commented on src/main/java/ru/practicum/shareit/request/impl/ItemRequestServiceImpl.java
> +        itemRequestDtos.forEach(this::setItemsToItemRequestDto);
Аналогичное замечание по сокращению количества запросов.

2023-07-09 23:47 UTC, dima-irqtsk commented
> Есть еще одна техника разработки - TDD(test driven development).

Да, я читал. Но у нас вместе с ТЗ дают тесты для постмана, так что у нас тоже в некотором роде TDD )

2023-07-10 03:25 UTC, dima-irqtsk commented on src/main/java/ru/practicum/shareit/request/impl/ItemRequestServiceImpl.java
> +    private void checkParameters(int from, int size) {
Я так и не понял, почему у меня в контроллерах не срабатывали аннотации @Min. Они пропускали значения меньше указанного и позволяли вызвать метод из сервисного слоя. Но в сервисе отдельная проверка этих параметров тоже не нужна, судя по всему. Потому что далее from и size преобразуются в объект PageRequest, а он не примет неверные параметры и выбросит исключение типа «IllegalArgumentException: Page index must not be less than zero».
Поэтому свой метод валидации входных значений я убрал и аннотации не стал ставить.

2023-07-10 15:03 UTC, dima-irqtsk commented on src/main/java/ru/practicum/shareit/request/impl/ItemRequestServiceImpl.java
> +        itemRequestDtos.forEach(this::setItemsToItemRequestDto);
Это очень важное замечание, спасибо )
Исправил.

2023-07-10 15:10 UTC, dima-irqtsk commented on src/main/java/ru/practicum/shareit/request/impl/ItemRequestServiceImpl.java
> +    private void checkParameters(int from, int size) {
В контроллере букинга тоже есть параметры запроса from и size, я решил и туда прикрутить аннотации. И там они тоже не заработали, я так и не понял почему.

2023-07-10 17:43 UTC, ohelly approved these changes
Привет! Все супер, замечания исправлены. Работу принимаю, можно двигаться дальше!
По Min и Max пока нет времени посмотреть, но мне самому стало интересно. Как доберусь гляну

2023-07-11 04:47 UTC, merged