Add docker
dima-irqtsk/java-shareit pull request #4
Opened 2023-07-19 09:37 UTC by dima-irqtsk

2023-07-19 19:30 UTC, ohelly requested changes
Привет! Отличная работа, все работает корректно, замечаний нет. Оставил три рекомендации - их выполнение, как обычно, на твое усмотрение.

2023-07-19 19:30 UTC, ohelly commented on gateway/pom.xml
> +            <artifactId>spring-web</artifactId>
Рекомендация: Данная зависимость уже есть, она на 54 строке. К тому же их вообще можно удалить, так как уже есть spring-boot-starter-web

2023-07-19 19:30 UTC, ohelly commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +public class BookingClient extends BaseClient {
Рекомендация: Клиент можно написать с использвоанием feign(https://www.baeldung.com/spring-cloud-openfeign)
Или с использованием webClient(зависимость webFlux)
С ними придется писать намного меньше кода

2023-07-19 19:30 UTC, ohelly commented on server/src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +public class ErrorHandler {
Рекомендация: Можно еще добавить обрабочтик всех осталььных ошибок, которые тут не перечислены(Throwable) и возвращать internal server error

2023-07-20 10:04 UTC, dima-irqtsk commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +public class BookingClient extends BaseClient {
Влад, это отличный совет, и я обязательно это изучу. Но в этом спринте базовый клиент был дан нам Практикумом, поэтому здесь использован именно он. Наверное, это чтоб мы в большей степени руками поколупали его )
К сожалению, сейчас не найду времени переписать, используя эту рекомендацию (
Остальные замечания внес.

2023-07-20 19:16 UTC, ohelly approved these changes
Привет! Все отлично, работу принимаю. Можно двигаться дальше!

2023-07-21 11:35 UTC, merged